project_id = "blpbeopmdfahiosglomx"

[functions.send-email]
verify_jwt = false

[functions.send-producer-notifications]
verify_jwt = true

[functions.check-leaderboard-access]
verify_jwt = true

[functions.create-leaderboard-checkout]
verify_jwt = true

[functions.verify-leaderboard-checkout]
verify_jwt = true

[functions.leaderboard-customer-portal]
verify_jwt = true

[functions.leaderboard-stripe-webhooks]
verify_jwt = false

[functions.stripe-setup-check]
verify_jwt = true

[functions.check-grace-periods]
verify_jwt = false

[functions.admin-ban-account]
verify_jwt = true

[functions.admin-revoke-ban]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.backfill-missing-submissions]
verify_jwt = true

[functions.admin-confirm-payment]
verify_jwt = true

[functions.merge-producers]
verify_jwt = true

[functions.create-escrow-payment-link]
verify_jwt = true

[functions.create-escrow-checkout]
verify_jwt = false

[functions.send-liability-notification]
verify_jwt = true

[functions.process-liability-claim]
verify_jwt = false

[functions.send-manual-producer-email]
verify_jwt = true
