
-- Create production_companies reference table
CREATE TABLE public.production_companies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.production_companies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access" ON public.production_companies FOR SELECT USING (true);
CREATE POLICY "Admin write access" ON public.production_companies FOR ALL USING (public.has_role(auth.uid(), 'admin'::app_role));

-- Seed production company names
INSERT INTO public.production_companies (name) VALUES
  ('Drive International Agency'),
  ('Vision Bank'),
  ('FYM Agency'),
  ('Better Days'),
  ('On The Map Creative'),
  ('X Studio'),
  ('Snapchat'),
  ('Campsight Studios'),
  ('Black Screen Productions'),
  ('Impulsive Films'),
  ('Insomniac'),
  ('OnSet Gringos'),
  ('Mrok Films'),
  ('Open Range Crew'),
  ('Rose and Key Productions'),
  ('Flamingo House'),
  ('The Rhino Farm'),
  ('Monkey Bars'),
  ('FYM'),
  ('Happy I''m Sad'),
  ('Lately Early Productions'),
  ('Clean Sweep Entertainment'),
  ('SicLogic Records'),
  ('GDE'),
  ('Miss Everything Entertainment'),
  ('True Vision Media Group'),
  ('ALO YOGA'),
  ('BlackWax'),
  ('BELLA+CANVAS'),
  ('Creature Films / Entertainment One'),
  ('OneWheel'),
  ('Bliss Bears Entertainment'),
  ('HappyImSad'),
  ('Greenpoint Pictures'),
  ('VB Films'),
  ('Blue Ox Films'),
  ('Ty Rogers LLC'),
  ('ShooterCo.'),
  ('Happy Place'),
  ('Sturdy Co.'),
  ('TOUCHSTONE'),
  ('Grade A Productions'),
  ('ALO'),
  ('Times10'),
  ('SturdyCo.'),
  ('Immortals F.C.'),
  ('GrandStandPictures'),
  ('Thirsty Whale Productions'),
  ('Moment House'),
  ('BRAVE Media'),
  ('Spike DDB'),
  ('Left Productions'),
  ('Snog Productions'),
  ('Daylight'),
  ('YBTG'),
  ('Yes Chef Pictures'),
  ('Keemotion Films'),
  ('No Love Out West'),
  ('Beyond Collective'),
  ('All Minds'),
  ('SEED Media Arts'),
  ('Honor The Gift'),
  ('NOW OPEN'),
  ('Ample Creative'),
  ('North of Now'),
  ('MoonManEnt'),
  ('Reel Goats'),
  ('Shot Clock'),
  ('BT Studios'),
  ('IRIS'),
  ('ISHKO ENT.'),
  ('Designory'),
  ('Beyond Studios'),
  ('IRIS-World'),
  ('Chiat Day'),
  ('MoonManEnt.'),
  ('Sink or Swim Creative'),
  ('ShotClock'),
  ('Roughhouse'),
  ('Black Screen'),
  ('MATTE Projects'),
  ('Paperboy Media Group'),
  ('Cult Classic TV'),
  ('Sink Or Swim Creative'),
  ('Kids Never Grow Old'),
  ('The Soze Agency'),
  ('Grade A'),
  ('OneThirtyEight Productions'),
  ('No Wheelies'),
  ('Dunn Rite Productions'),
  ('Seed Media Arts'),
  ('Honeycomb Films'),
  ('NVSN Productions'),
  ('KeyTV'),
  ('DNI Productions'),
  ('Sink Or Swim'),
  ('J3K Logistics Co.'),
  ('Piecemill Co.'),
  ('FiveTwelve Pictures'),
  ('POV'),
  ('OSUN'),
  ('BEL Entertainment Co.'),
  ('MVA'),
  ('LAFC'),
  ('Milo & Curtis'),
  ('727 Films'),
  ('Snap Inc.'),
  ('Silver Spoon Creative'),
  ('Big Kid'),
  ('Combs Global'),
  ('The Immigrant Film'),
  ('Anaheim Studios'),
  ('Grade A Films'),
  ('Solace Creative'),
  ('MINDofLARU'),
  ('Sat & Friends'),
  ('Paperwork Studio'),
  ('Frequency Collective'),
  ('Noire Creative'),
  ('DOJOHOUSE'),
  ('Jerry Productions'),
  ('Drive Internation Agency'),
  ('625 Industries'),
  ('StudioNow'),
  ('Stept Studios'),
  ('Mirror Box'),
  ('Yes Chef'),
  ('Rseolve Media Group'),
  ('Cold Creator'),
  ('YORK Productions'),
  ('Bezé Studios'),
  ('Projekt Studios'),
  ('QuickStrike Studios'),
  ('Stained Studios'),
  ('No Name Collective'),
  ('Blank Square Productions'),
  ('Bullseye Production'),
  ('The Genius Club'),
  ('COCO BUTTER'),
  ('Jackson Guitars'),
  ('Tre Native'),
  ('Kin Films'),
  ('Kaleidodope Visions'),
  ('Collage Montage'),
  ('Riverside Entertainment'),
  ('Uninterrupted'),
  ('Creators Lab'),
  ('Daniel Carberry Films'),
  ('ZHILYOVA'),
  ('Transit Pictures'),
  ('RD Media House'),
  ('DBM Productions'),
  ('Let It Rip Pictures'),
  ('DATE'),
  ('NowFuss'),
  ('Junivis'),
  ('Casamare Filmworks'),
  ('BillionDollarBaby Productions'),
  ('Bullseye Productions'),
  ('You Got Jokes'),
  ('UnderWonder Content'),
  ('CEKAI'),
  ('9Muses'),
  ('ArtClass'),
  ('Sincerely Yours Darling'),
  ('Fearpix'),
  ('BuffNerdsMedia'),
  ('Made By Heirs'),
  ('One Machine'),
  ('555 Productions'),
  ('Libertine Studios'),
  ('AMP x BT.Studios'),
  ('SUPERFRIENDS'),
  ('The Desire Company'),
  ('MARK BARZ'),
  ('FENDER'),
  ('RED GLASS MEDIA'),
  ('PULSE'),
  ('DBM Creatives'),
  ('BASEWOOD')
ON CONFLICT (name) DO NOTHING;
