// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { validateEnv, validateEnvFormats, testSupabaseConnection } from '@/config/env';

// Export connection test function for use in App
export { testSupabaseConnection };

const envStatus = validateEnv();
const formatValidation = envStatus.ok ? validateEnvFormats() : null;

// Warn about format issues but don't block initialization
if (formatValidation && !formatValidation.valid) {
  const issues = 'issues' in formatValidation ? formatValidation.issues : [];
  console.error(
    "[SUPABASE CONFIG WARNING] Environment variable format issues detected:",
    issues
  );
  console.error(
    "[SUPABASE CONFIG WARNING] The app may not work correctly. Please verify:",
    "\n  - VITE_SUPABASE_URL should be: https://xxxxx.supabase.co",
    "\n  - VITE_SUPABASE_PUBLISHABLE_KEY should be the 'anon' public key (not service_role)"
  );
}

/**
 * Supabase client instance
 * 
 * Will be null if required environment variables are missing.
 * This prevents the app from crashing when configuration is invalid.
 * 
 * Note: Even if client is created, it may not be able to connect.
 * Use testSupabaseConnection() to verify connectivity.
 * 
 * Always check if supabase is null before using it, or rely on
 * the App-level validation that prevents the app from rendering
 * when env vars are missing.
 */
export const supabase = envStatus.ok
  ? createClient<Database>(
      import.meta.env.VITE_SUPABASE_URL,
      import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
      {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        }
      }
    )
  : null;